### ISSUE TITLE
Where is z88dk-dis.exe?

### ISSUE THREAD

**Issue by obiwanjacobi** [z88dk/z88dk#1042]
I can't find it in bin or anywhere else!

https://github.com/z88dk/z88dk/wiki/Tool-z88dk-dis

**Comment by suborb** [comment]
It’s built from the code in src/ticks on Linux/Mac builds it should end up in bin. 

It should also on the nightlies subject to be not forgetting to copy it.

**Comment by aralbrec** [comment]
It is in the windows nightly too and it did build for me a couple days ago via visual studio on windows.

**Comment by obiwanjacobi** [comment]
I'm not using the nightly builds...

**Comment by obiwanjacobi** [comment]
When I install the latest (31-12-2018) build I got loads of errors.
So I reverted back to 1.99B and just copied over the binaries that were in the nightly but not in the 1.99B release (which are quite a few).

**Comment by obiwanjacobi** [comment]
The map file does not seem to be used?

I can see the on label being used at the very start, but after that only raw addresses are shown?

```asm
TAR__clib_malloc_heap_size:
                    di                                      ;[0000] f3
                    jp      $0074                           ;[0001] c3 74 00
                    nop                                     ;[0004] 00
                    nop                                     ;[0005] 00
                    nop                                     ;[0006] 00
                    nop                                     ;[0007] 00
                    jp      $0071                           ;[0008] c3 71 00
                    nop                                     ;[000b] 00
                    nop                                     ;[000c] 00
                    nop                                     ;[000d] 00
                    nop                                     ;[000e] 00
                    nop                                     ;[000f] 00
                    jp      $0071                           ;[0010] c3 71 00
                    nop                                     ;[0013] 00
                    nop                                     ;[0014] 00
                    nop                                     ;[0015] 00
                    nop                                     ;[0016] 00
                    nop                                     ;[0017] 00
                    jp      $0071                           ;[0018] c3 71 00
                    nop                                     ;[001b] 00
                    nop                                     ;[001c] 00
                    nop                                     ;[001d] 00
                    nop                                     ;[001e] 00
                    nop                                     ;[001f] 00
                    jp      $0071                           ;[0020] c3 71 00
                    nop                                     ;[0023] 00
                    nop                                     ;[0024] 00
                    nop                                     ;[0025] 00
                    nop                                     ;[0026] 00
                    nop                                     ;[0027] 00
```

**Comment by suborb** [comment]
There was an issue parsing older map file formats - all addresses were ending up as 0!

More generally, there have been a large number of improvements and bug fixes since 1.99B - in particular, given your aims, some substantial changes to sccz80 - so I'd really recommend moving to a nightly - the problems above look like you need to give a -Ca-I[path] option to point to the directory where config_private.inc is located.

**Comment by aralbrec** [comment]
```
Error at file 'alloc/malloc/z80/asm__falloc.asm' line 15: cannot read file 'config_private.inc'
```

These errors have to do with a missing `config_private.inc` during the library build process.  This file is copied to `libsrc/_DEVELOPMENT` from the target's directory, eg, `libsrc/_DEVELOPMENT/target/zx/config_zx_private.inc`.  This file is in turn automatically created from config files in the target's config directory and it will contain all the constant defines for the machine.  The way targets are defined was changed to be more flexible since 1.99B and I think your own target definition is no longer complete anymore.

There isn't much to change but I can have a look today or tomorrow to detail what changes need to be made.

**Comment by suborb** [comment]
I'll close this one since z88dk-dis has been found...
