### ISSUE TITLE
Double cursor when entering text

### ISSUE THREAD

**Issue by DarwinNE** [z88dk/z88dk#1357]
Hi to all,
  I noticed that on several platforms, a "double cursor" is shown when text is entered following a call to fgets_cons. Here is a minimal code that should shows this behaviour:

~~~~
#include<stdio.h>
#define SIZE 80

int  main(void)
{
    char buffer[SIZE];
    fgets_cons((buffer),(SIZE));

    printf("You typed: %s\n",buffer);
    return 0;
}
~~~~

If I compile for the MSX target with

~~~~
zcc +msx -create-app bug.c -lndos -zorg=32768 -o bug
~~~~

Instead of getting a single cursor, I get both an underline and a block. Here is an example of what I get running the previous code and typing "testing".

![doble_cursor_msx1](https://user-images.githubusercontent.com/11355790/71307763-53500680-23f3-11ea-9f61-804fabd7764a.png)

The input works fine, though, but the double cursor is somewhat inelegant :-)
I have been reported that the same behaviour occours on the CP/M target using fgets with stdin, I think it comes from the same origin. Here is the double cursor after ">" on one of my programs running on a Kaypro CP/M computer:

![ELsvZrJWkAEP5o7](https://user-images.githubusercontent.com/11355790/71307802-d3766c00-23f3-11ea-822f-4b0990e382a6.jpeg)

Cheers,
D.

**Comment by suborb** [comment]
Yes, I know the cause of that one.

The `fgets()` implements a simple software cursor (the `_`) so if the firmware implements one as well you end up with both of them.

If you switch to the cross platform VT52 engine (`--generic-console`) then the firmware cursor is  disabled since we bypass firmware printing and hit the hardware directly. As a result, you only end up with one cursor.

However, the problem persists if you use firmware routines so I'll add a compile time flag to disable printing of the software cursor to work around that one. I'm in the middle of adding another DDR machine but I'll pick it up next, so probably a couple of days.

**Comment by DarwinNE** [comment]
Thank you very much!

**Comment by suborb** [comment]
I've added a compile time pragma to disable the soft cursor in `fgets_cons()` - just add the following option:

**Comment by DarwinNE** [comment]
Thank you, I'll check as soon as possible!

**Comment by DarwinNE** [comment]
Hello,
  I tested my program, made a git pull and compiled from sources z88dk (v15793-0eaa84cff-20191225), but I am still getting the double cursor.

I compiled the program with the following command:
~~~~
zcc  +msx -create-app -subtype=msxdos -zorg=32768 -pragma-define:CLIB_DISABLE_FGETS_CURSOR=1  bug.c -o bug
~~~~

Cheers,
D.

**Comment by suborb** [comment]
Hi Davide, I've just checked the behaviour on the MSX and I can't see the double cursor - did you rebuild msx_clib.lib? To do so go into libsrc and then enter the following commands:

    rm msx_clib.lib
    make msx_clib.lib
    cp msx_clib.lib ../lib/clibs/

**Comment by DarwinNE** [comment]
Hi,
  I checked again and indeed it was my fault! I was using an outdated file.
Everything is working perfectly now, thank you very much!
D.

**Comment by suborb** [comment]
No worries. I’m glad to hear that it’s all good now.
