### ISSUE TITLE
zsdcc patch changes in SDCCopt.c?

### ISSUE THREAD

**Issue by spth** [z88dk/z88dk#1497]
I've just had a quick look at the current zsdcc patch at https://github.com/z88dk/z88dk/blob/master/src/zsdcc/sdcc-z88dk.patch
I see the point in the most of the changes, but I wonder about SDCCopt.c. As far as I can see nearly all changes in there are just a matter of coding style.
I wonder if it would be better to just leave out the cosmetic SDCCopt.c part from the patch, as it seems like unnecessary distraction for those wanting to know how zsdcc behaves differently from sdcc.

The one non-cosmetic change in SDCCopt.c is the memcpy() vs __memcpy() one. And that one looks like a problem to me: It results in calls to a function called memcpy(). However, code that does not include <string.h>, nor contains an external declaration for memcpy() is free to use memcpy() as the name of something that has non-external linkage.
E.g. C code would be allowed to have a static memcpy() function in a file that does not include <string.h> and the change in the zsdcc patch would result in the compiler inserting calls to that static memcpy(), assuming that this static memcpy() written by the user behaves just as standard memcpy(). Obviously that results in bugs if the user's static memcpy() behaves differently from standard memcpy(). And that difference in behaviour would probably the reason the user wrote a static memcpy() in the first place.

**Comment by feilipu** [comment]
I think the reason for the patch is to use the [z88dk memcpy()](https://github.com/z88dk/z88dk/blob/e7f35227929eac76c2ce7de25d67b05733802c66/libsrc/_DEVELOPMENT/string/z80/asm_memcpy.asm) rather than the [sdcc memcpy()](https://sourceforge.net/p/sdcc/code/HEAD/tree/trunk/sdcc/device/lib/__memcpy.c).
The Intel 8080 code is in there for older targets, and it uses (optionally) [unrolled z80 LDI](https://github.com/z88dk/z88dk/blob/e7f35227929eac76c2ce7de25d67b05733802c66/libsrc/_DEVELOPMENT/l/z80/l_ldi.asm) instructions for performance.

There's another discussion #1479, where I've caused a problem by losing some of the patches that were in our older patch against r9958. Some of the patches you've added to the mainline SDCC code. But I'm not able to bisect what was left out, and whether it was in fact important somehow.
