### ISSUE TITLE
[super80][bug] Bitbang breaks the game (black screen after playing a sound)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#1602]
Bit-bang sound routines produce sounds but produce a black screen during gameplay on the super80 target but the game may be running even after the black screen as I can hear some sounds.

**Comment by suborb** [comment]
It looks like this affects the models without an MC6845 (so Super-80, Super-80d, Super-80e, Super-80m). Bit 2 of port $f0 controls whether the screen is set or not on those models and is used for paging in colour on the Super 80v.

There's some model detection in the crt0: https://github.com/z88dk/z88dk/blob/master/lib/target/super80/classic/super80_crt0.asm#L113 which toggles that bit to detect whether colour is available on the MC6845 models.

That bit of model detection should really only take place with -clib=vduem otherwise the bit ends up being reset and the screen is turned off when sound is played.
