### ISSUE TITLE
make DESTDIR doesn't regenerate src/config.h

### ISSUE THREAD

**Issue by ColinPitrat** [z88dk/z88dk#1752]
After cloning the repository, if I want to install somewhere else than /usr/local, I have to do:

```
rm src/config.h
make DESTDIR=/some/path install
```

If I don't do the rm, the target is installed in /some/path but look for the data in `/usr/local/share`.
Moreover, if I already did a build with a different DESTDIR, I have to do a `make clean` to ensure it rebuilds everything with the new path.

The ideal behavior would be:
 - make always regenerate `src/config.h` (for example making it PHONY)
 - files that depend on `src/config.h` are rebuilt if (and only if) its content changed (I suppose this means overwriting it only if it changes, so generating a `src/config.h.new` and only moving it in place of `src/config.h` if it's different)

Note: this is of course the same if I use `build.sh -i /some/path`.

**Comment by suborb** [comment]
I've added in the missed dependency tracking for zcc so that anything binaries are rebuilt when src/config.h changes which was missing.

I can't quite think how to do the `src/config.h` in a neat way that doesn't break non-git connected builds or force needless rebuilds without an extra file floating around the place. 

However, it's not strictly necessary to do this, the tree can be located anywhere so long as the environment variable `ZCCCFG` is defined - all paths are worked out relatively from that.
