### ISSUE TITLE
(sam) Keyboard input difference compared to ZX

### ISSUE THREAD

**Issue by dandoore** [z88dk/z88dk#1756]
I have been trying to use kbhit() followed by getch() to capture keystokes and SAM seems to be extremely sensative compared to the same code under ZX;

```
#include <stdio.h>
#include <conio.h>

void main()
{
	clrscr();
    char ch;
    while (1)
		{
		if ( kbhit() )
			{
			ch = getch();
			if (ch == 'x') break;
			printf("%c",ch);
			}
		}
	printf("\nEnd.\n");
}
```
Pressing keys alphabetically at normal speed gives this on ZX;

![SNAPZX](https://user-images.githubusercontent.com/43847005/114278569-5f1c6d80-9a28-11eb-90ec-ebc0f886d293.PNG)

And this on SAM

![simc0129](https://user-images.githubusercontent.com/43847005/114278587-6e9bb680-9a28-11eb-8b41-d60cbc862993.png)

ZX loses some keystrokes (g&h didn't register) but SAM goes like it has an auto-repeat of 0ms!

If you take out the 'if kbhit()' condition to just make it just read and echo characters it works as you would expect:

![simc0130](https://user-images.githubusercontent.com/43847005/114282289-de1aa180-9a3a-11eb-8491-0e6006cb7084.png)

**Comment by suborb** [comment]
So I suspect you'll see the same behaviour on the +zx if you compile with `--hardware-keyboard`.

`kbhit()` reads the instantaneous state of the keyboard and then stores any keypresses to be picked up with `getch()`. If there's no keypress stored, `getch()` calls `fgetc_cons()`

With +zx by default we read the state of the keyboard by looking at (23560) which is of course updated by the ROM, after debouncing etc

On the Sam and with --hardware-keyboard there's no debouncing with `kbhit()`, but there is with `fgetc_cons()` so that's why you're seeing the different result.

**Comment by dandoore** [comment]
I've not specified  `--hardware-keyboard` so I presume this is default behaviour but for the ZX it's not - is there a way to get the debounced input on SAM for kbhit() so that I can act on the kbhit() (in this case, `break` out of a loop) and then getch() the character out of the buffer?

**Comment by dandoore** [comment]
Awsome, [that](https://github.com/z88dk/z88dk/commit/eade0617f577d05c7ceb8f019e7fee23b0bdb511) fixes the issue :)
