### ISSUE TITLE
Wrong warning using ZSDCC and GameBoy target

### ISSUE THREAD

**Issue by Oleg-N-Cher** [z88dk/z88dk#1821]
zcc +gb -create-app -compiler=sdcc -o gbdemo.gb gbdemo.c

> Warning at file 'gbdemo.c' line 578: integer '65344' out of range
> Warning at file 'gbdemo.c' line 580: integer '65344' out of range
> Program requires cartridge with 2 ROM banks
> Notice: Available RAM space is 7928 bytes ignoring the stack
> Adding main banks 0x00,0x01 (25688 bytes free)

After compiling [gbdemo.zip](https://github.com/z88dk/z88dk/files/6852379/gbdemo.zip)

Yesterday nightly build of z88dk for Windows was used.

Wrong lines look as:

![image](https://user-images.githubusercontent.com/1090608/126421719-176dfdfd-92a2-448d-9352-b25f75dc1304.png)

**Comment by suborb** [comment]
Looking at the z80asm test files, it looks like z80asm expects the numeric parameter to be in the range 0-255 rather than actually pointing to the $ff00 page.

For sdcc this can probably be fixed up in the translation rules, but I do suspect that a similar problem may exist with sccz80 when it uses expressions rather than constants.

@pauloscustodio - could you take a look at fixing up z80asm?

**Comment by pauloscustodio** [comment]
According to http://www.devrs.com/gb/files/opcodes.html, the warning is correct, as the instructions are described as:
`LDH (n),A | ($FF00+n) <-- A`
`LDH A,(n) | A <-- ($FF00+n)`

Is this source correct? If yes, the source code should be changed to
`LDH A, (0xFF40 & 0xFF)`

To fix z80asm I need to create a new record type in the object file and update the linker and z80nm to handle these high-page addresses.

**Comment by pauloscustodio** [comment]
Fixed. Now z80asm accepts either a value in the range 0x00..0xff or 0xff00,,0xffff
