### ISSUE TITLE
git sandbox dirty after build

### ISSUE THREAD

**Issue by vext01** [z88dk/z88dk#210]
From a clean source tree, after building two files are marked modified according to git:

```
arrakis> git status
On branch openbsd
Your branch is up-to-date with 'origin/openbsd'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   lib/config/zcc.cfg
        modified:   src/config.h
```

If these files are auto-generated, would it not be best to not include them in git?

**Comment by aralbrec** [comment]
Currently src/config.h is committed for the windows build using VS2015.  This is because the VS2015 build is not automatically making it so it acts as a default for windows.  Maybe we can look into that.

I'm not sure we need lib/config/zcc.cfg.  What it's there for is to select a default z80 target if one is not supplied on the compile line ("zcc +zx ...", "zcc +msx ...", "zcc +cpm ....", "zcc ..." = default z80 build currently the z88 via zcc.cfg).  Maybe we should just error out if there is no z80 target supplied?

**Comment by suborb** [comment]
> On 29 Apr 2017, at 14:03, aralbrec <notifications@github.com> wrote:
> 
> Currently src/config.h is committed for the windows build using VS2015. This is because the VS2015 build is not automatically making it so it acts as a default for windows. Maybe we can look into that.
> 
That can probably go into win32/ and the include paths of the projects updated to search there as well. 
> I'm not sure we need lib/config/zcc.cfg. What it's there for is to select a default z80 target if one is not supplied on the compile line ("zcc +zx ...", "zcc +msx ...", "zcc +cpm ....", "zcc ..." = default z80 build currently the z88 via zcc.cfg). Maybe we should just error out if there is no z80 target supplied?
> 
Agreed.

**Comment by vext01** [comment]
Thanks! I've now submitted all of my bug reports. Sorry to rock the boat :)

**Comment by suborb** [comment]
No worries. They are all valid and look easy to sort out.

**Comment by vext01** [comment]
Do you guys hang in an IRC channel btw?

**Comment by aralbrec** [comment]
Not unless it's being kept secret from me....

**Comment by suborb** [comment]
zcc.cfg went in via #218.

As mentioned above, config.h for win32 should move to the win32 directory.
