### ISSUE TITLE
Incorrect/misleading compiler error when ZCCCFG not set

### ISSUE THREAD

**Issue by stevesims** [z88dk/z88dk#2298]
On attempting to install on OS X I failed to follow the instructions correctly and skipped over the step to set up a ZCCCFG environment variable.  When I attempted to compile the simple C test file I encountered the following error:

```
➜  z88dk zcc +zx -vn test.c -o test.bin -lndos  
error: file open: ndos.lib
```

I found this error misleading, as I interpreted it as the a failure to open the file because the file was already open.

I'd suggest a couple of things from this.

Firstly ideally if ZCCCFG has not been set, then an error should be displayed to reflect that.

Secondly the nature of the "file open" error should be displayed; in this case presumably the true error was that the ndos.lib file could not be found, and thus could not be opened.

**Comment by suborb** [comment]
I've put on the z80asm label since that's where the error is coming from, and yes it is misleading.

Just as a note, it's not possible to warn that ZCCCFG isn't configured - there's a couple of ways in which everything works without it being configured:

1. Install to the filesystem - it will use the built in path (eg /usr/local/share/z88dk/lib/config as a proxy for ZCCCFG)
2. Launch zcc with /path/to/zcc it will then use /path/to/../lib/config as a proxy for ZCCCFG
