### ISSUE TITLE
(Discussion) Next stable release when?

### ISSUE THREAD

**Issue by atirut-w** [z88dk/z88dk#2375]
The latest commit I could get to build is b4d8501429c246249af5fb8ff4ab4b7e69909a84. Current latest commit(1df911db3a6f20f1b979f3c6f1afe85e68f005fb) failed to past tests.

It would be nice if we could get a stable release soon because god knows if the latest building commit is even stable. There's also the problem about how the docs kept changing even though the version used with them aren't even stable enough yet.

**Comment by suborb** [comment]
> The latest commit I could get to build is https://github.com/z88dk/z88dk/commit/b4d8501429c246249af5fb8ff4ab4b7e69909a84. Current latest commit(https://github.com/z88dk/z88dk/commit/1df911db3a6f20f1b979f3c6f1afe85e68f005fb) failed to past tests.
> It would be nice if we could get a stable release soon because god knows if the latest building commit is even stable

Given that a clean checkout builds and tests on armhf, arm64, ppc64el, s390x, amd64 Ubuntu variants, amd64 Alpine, macOS (amd64 and arm64) and Cygwin this suggests an environmental issue or setting.

Unfortunately, without any further information it's impossible to investigate your issue.

> There's also the problem about how the docs kept changing even though the version used with them aren't even stable enough yet.

As a result of nightly builds being published across multiple channels for multiple platforms, documentation tracks latest. Due to the lack of support for branches in GitHub wikis it may lead for a few days until a feature is merged.
