### ISSUE TITLE
z80asm: show source code version in z80asm

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#259]
Clone of #258 for z80asm

Add output of ```git rev-list --count HEAD``` to version information.

**Comment by aralbrec** [comment]
Four programs do not build including z80asm under vs2015.  For z80asm it looks like the prebuildevent is under the win32 debug version only and may work if you are only doing win32 debug builds.  I don't think the other builds will see this file if either z80asm doesn't build or z80asm isn't first in the build list.

I think the only solution is to introduce a dummy project whose sole purpose is to build that config file and then have all other projects depend on it.

I'm not going to try that now but I will commit config.h temporarily so that vs2015 builds can be done.  I think it's better to have something in the version string instead of nothing with vs2015 so I'm going to restore the build date, etc, in that file by default.

**Comment by pauloscustodio** [comment]
I've temporarily reverted to the previous solution until a better one is implemented.

**Comment by pauloscustodio** [comment]
Can we assume there is Perl installed in the windows machines used for building z88dk?
If yes, I can make a platform-independent Perl script that builds src/config.h. This script can then
be called from build.sh, from the top level Makefile, from Visual Studio, and from any module's Makefile that needs config.h.

**Comment by aralbrec** [comment]
I think it's preferable to try to do this for a base win32 system (ie deprived of almost everything).  There should be some not-insane way of doing this for vs.

**Comment by pauloscustodio** [comment]
There's one that always works: make a C program that builds config.h; compile it and run it as part of the build process. We can keep it together with the config.h, maybe make_config.c.

Any better ideas?

**Comment by aralbrec** [comment]
I'm thinking about making a dummy project in the solution called "config" or similar with the sole purpose of making config.h using a PreBuildEvent like you had in z80asm.  Then have all the other projects depend on it (zcc, z80asm, etc) so that it is always made before each binary is built.

There are some issues in visual studio with the command line build process being different from the IDE process but I think the above will work for both.  I see that @zx70 has a vsbuild.cmd in the main directory for building from the command line using vs.
