### ISSUE TITLE
zcc has the line count wrong

### ISSUE THREAD

**Issue by pauloscustodio** [z88dk/z88dk#353]
See #344

**Comment by pauloscustodio** [comment]
Line count wrong comes from zcc:

test.c
```
int main() {
	int a = 256;
	int b = 256;
	int c = a * b;
	return c;
}
```
```zcc +z80 test.c -otest.bin > nul``` results in:

```
test.c:5: warning 165: integer overflow in expression
```

**Comment by aralbrec** [comment]
(The compiler for the following line is zsdcc rather than sccz80)

> zcc +z80 test.c -otest.bin > nul results in:
> test.c:5: warning 165: integer overflow in expression

The line number is correct because the compiler has optimized all statements away except the return, where the problem is reported.

247   0000              _main:
248   0000              ;zzz.c:5: return c;
249   0000  21 00 00    	ld	hl,0x0000
250   0003  C9          	ret

**Comment by aralbrec** [comment]
I've retested the original problem code and the line number problem has gone away.
