### ISSUE TITLE
z80asm: request ALIGN directive

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#436]
We have [page aligned sections](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/target/crt_memory_model_z180.inc#L70), but unless the CRT specifies a specific page aligned starting address via `__crt_org_data`, then the [`SECTION DATA`](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/target/crt_memory_model_z180.inc#L54) doesn't start on a page boundary.

The linker / appmake gives a warning, but it would be nice to have a way to have this padding calculation  `ASMPC-(ASMPC&0xff)+0x100` done auto-magically, irrespective of the `SECTION CODE` size, to have `SECTION DATA` start at the correct place on a new page.

This could be part of the bank memory conversation for appmake #425.

Thanks in advance.

**Comment by aralbrec** [comment]
Movement of the org has to come from the linker.  What's being asked for here is an align directive.

This will probably be another property of a section:  org/no-org, phase/no-phase, align/no-align.  The idea is to specify an alignment for a section such that the linker will move the section org forward with padding if the address isn't correctly aligned.

We may also want to inline and align directive in regular code (as is done with phase).  However, such an unlined align, unless you can store the alignment at a point in the object file, will likely have to behave like ASMPC, as in it will align/pad according to the current local byte counter rather than the final address.  I don't know if that is very useful (we do this now with devices like `defs 0x100 - ASMPC&0xff`, etc.
