### ISSUE TITLE
Z180 - use of undocumented Z80 instructions in stdio

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk#729]
Chasing some failures in the use of the stdio library with YAZ180, I noted that [`asm_fflush.asm`](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/stdio/z80/asm_fflush.asm#L51) uses some undocumented Z80 op-codes, that aren't supported on the Z180. Ouch.

EDIT: This was a solitary case for `asm_fflush.asm`.
The other undocumented opcodes are avoided in the Z180 case.
```
phillip:~/Z80/z88dk/libsrc/_DEVELOPMENT$ rgrep ixl stdio/
stdio/z80/asm_fflush.asm:   ld a,ixl

phillip:~/Z80/z88dk/libsrc/_DEVELOPMENT$ rgrep ixh stdio/
stdio/z80/asm_fflush.asm:   or ixh
```
Fix
```
IF __CPU_Z180__ || __CPU_R2K__ || __CPU_R3K__
   push ix
   pop hl
   ld a,l
   or h
   jp z, asm__fflushall
ELSE
   ld a,ixl
   or ixh
   jp z, asm__fflushall
ENDIF
```

**Comment by aralbrec** [comment]
The assembler is supposed to generate errors for all the undocumented instructions when in z180 mode.  I'll fix that one and open a new issue for z80asm.

**Comment by aralbrec** [comment]
There is no error in the library itself:

[code]
Object  file z180.lib at $134FB8: Z80RMF11
  Name: asm_fflush
  Section code_clib: 0 bytes
  Section code_stdio: 0 bytes
  Symbols:
    L C $0000 __CLIB_OPT_MULTITHREAD (section "") (file config_private.inc:143)
    L C $0000 __CLIB_OPT_STDIO (section "") (file config_private.inc:205)
    G = $0000 asm_fflush (section code_stdio) (file stdio/z80/asm_fflush.asm:86)
  Externs:
    U         asm_fflush_unlocked
  Expressions:
    E =  $0000 $0000: asm_fflush := asm_fflush_unlocked (section code_stdio) (file stdio/z80/asm_fflush.asm:86)
[/code]

This is because "asm_fflush" is being aliased to "asm_fflush_unlocked", which happens when the [multi-threading option](https://github.com/z88dk/z88dk/blob/master/libsrc/_DEVELOPMENT/stdio/z80/asm_fflush.asm#L23) is off (and it must be off because it's not implemented!).

I verified that z80asm is catching the specific undocumented instructions in `asm_fflush.asm` using this test file:

zzz.asm
```
ld a,ixh
or ixl
ret
```

z80asm -b zzz.asm
assembles fine because it's in z80 mode

z80asm -b --cpu=z180 zzz.asm
generates errors:

```
Error at file 'zzz.asm' line 1: illegal identifier
Error at file 'zzz.asm' line 2: illegal identifier
2 errors occurred during assembly
```

So z80asm will catch any errors while assembling the library.

**Comment by feilipu** [comment]
Yes, this is not the issue I'm tracking down. Just noticed it in the process of elimination of other things.
(Unrelated code that used to work, that magically doesn't any more).

That this is aliased away is / was lucky. So the issue would only appear if multi-threaded Z180 library code were assembled, and then the assembler would have called out the error, immediately drawing attention.
