### ISSUE TITLE
[PC6001][UDG] Mode 1 produces black empty screen, Mode 2 produces fewer characters

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#876]
I am not getting the expected results on the PC6001 that I compile with
```
pc6001_32k_udg:
	$(Z88DK_PATH)$(MYZ88DK) +pc6001 $(SCCZ80_OPTS) -Cz--audio -clib=ansi -subtype=32k \
	-D__PC6001__ -v -DFULL_GAME \
	-DCONIO \
	-DFORCE_SCREEN_MODE=1 \
	-clib=default -pragma-redirect:fputc_cons=fputc_cons_generic \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	$(CROSS_LIB_PATH)/display/graphics_data/z88dk/xchase.asm \
	-lndos -create-app -o $(BUILD_PATH)/FULL_pc6001_32k_udg.prg \
	$(FULL_FILES)
	rm $(BUILD_PATH)/FULL_pc6001_32k_udg.prg
	rm $(BUILD_PATH)/FULL_pc6001_32k_udg.wav
	mv $(BUILD_PATH)/FULL_pc6001_32k_udg.cas $(BUILD_PATH)/FULL_pc6001_32k_udg.cp6
```

Mode 1 produces a blank black screen.

I have tested this with Virtual Nec Trek and select 2 pages at start-up.

**Comment by suborb** [comment]
Yup, that was an issue, should be fixed in 7c7d007bf2db41b270b87eb004200a787ee74688

I'm trying to come up with a way to handle the CSS flag in a portable way across the MC6847 targets, so at the moment mode 1 will come up with a green background and white foreground which is the colour scheme with the CSS flag reset.

If you really want it in white on black, then add 32, so mode = 33. This may well change, become documented etc at some point
