### ISSUE TITLE
[casio pv1000][redefined chars][bug] No re-defined characters 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#904]
I am getting no re-defined characters in my game.
Tested with Takeda's PV1000 emulator.

```
pv1000_light_udg:
	$(Z88DK_PATH)$(MYZ88DK) +pv1000 $(SCCZ80_OPTS) \
	-D__PV1000__ \
	-DZ88DK_JOYSTICK \
	-DCONIO_VT52 \
	-DCONIO \
	-lndos \
	-DANIMATE_PLAYER \
	-DUDG_GRAPHICS \
	-clib=default -pragma-redirect:fputc_cons=fputc_cons_generic \
	cross_lib/display/init_graphics/z88dk/udg/udg_init_graphics.c \
	cross_lib/display/graphics_data/z88dk/xchase.asm \
	$(LIGHT_FILES) \
	-create-app -o$(BUILD_PATH)/LIGHT_pv1000.bin
	rm $(BUILD_PATH)/LIGHT_pv1000.bin	
```
I am also getting no input (but this could be an emulator config issue).

![pv1000](https://user-images.githubusercontent.com/29057615/44671643-61bc2700-aa26-11e8-9eff-13428125a694.jpg)

**Comment by suborb** [comment]
Sorry, I forgot to mention this in the other issue because I knew it was going to be the next issue you raised! The font for the PV1000 is in a special format and needs to be located in the ROM so it doesn't work in the same way as the other targets.

Take a look at the wiki page: https://github.com/z88dk/z88dk/wiki/Platform---Casio-PV1000
