### ISSUE TITLE
[camputers lynx][create-app][tap] Frozen after load under Mame/Mess - Jynx complains about the tap format

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#908]
I am compiling my game with:
```
	$(Z88DK_PATH)$(MYZ88DK) +lynx $(SCCZ80_OPTS) \
	-DCAMPUTERS_LYNX \
	-vn \
	-DCONIO_VT52 \
	-DNO_COLOR \
	-DFULL_GAME -DSOUNDS \
	-DEND_SCREEN -DBETWEEN_LEVEL \
	-lndos \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES) \
	-create-app -o $(BUILD_PATH)/FULL_camputers_lynx.bin
```
which will produce a .tap file.

Mame/Mess 0.191
(mess64.exe lynx48k -window -uimodekey DEL)
can load the .tap with either MLOAD"" or LOAD""
but you get a frozen screen at the end of the tap.
(same result with lynx96k)

Jynx cannot load the .tap files:
"Failed to parse .tap file"

The old Pale emulator does not run on modern Windows.

**Comment by suborb** [comment]
The appmake issue was fixed in c041a6816c7c39e55d2538c7c924dd35e9301437 - the resulting .TAP file works in both Jynx and Pale (which works under wine).

In general, I think the Lynx could do with a bit of love. The following: http://www.russelldavis.org/CamputersLynx/files/Newsletters/Lynx%20User/Lynx%20User1.pdf has the information we need to:

1. Do a direct screen driver (use 8x8 fonts instead of the native 6x10)
2. Add graphics supports
3. Add inkey() keyboard support
4. One bit sound

**Comment by suborb** [comment]
Bear with me for a few days (and don't raise any issues yet!) I'm getting this machine working in a more standard way, so a familiar screen shot of what's on the way:

![screen shot 2018-09-02 at 22 50 57](https://user-images.githubusercontent.com/394721/44961090-01842400-af03-11e8-8c8d-9106f4badabf.png)

**Comment by suborb** [comment]
Hopefully what's in is good enough for Cross Chase.

I'm slightly dubious about the size of the screen - it looks bigger than the one in Mame but that can be adjusted easily enough.

**Comment by Fabrizio-Caruso** [comment]
@suborb only for the TINY version :-( 
The TINY(4.8k)  version loads and runs (with bad graphics as expected).
The FULL version (13k) starts loading and then freezes.
There must be a memory-related issue.
