### ISSUE TITLE
[vg5k][sdcc] Cross-Chase Build broken on snapshot 26/08/2018 (25th of August is OK)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [z88dk/z88dk#970]
My game starts with graphics glitches and then crashes if compiled with sdcc.

@suborb Is this issue possibly caused by https://github.com/z88dk/z88dk/commit/c4b36b66dd9c405964b76536bf30954f5088c611 ?

@suborb Do I have to change the compilation options for the vg5k with sdcc?

sdcc/vg5k has been broken starting at snapshot 26/08/2018:
20/08/2018: OK
23/08/2018: OK
25/08/2018: OK
26/08/2018: KO !!!
27/08/2018: KO 
10/09/2018: KO
14/09/2018: KO

I compile with:
```
	$(Z88DK_PATH)$(MYZ88DK) +vg5k \
	-compiler=sdcc \
	--opt-code-size \
	--reserve-regs-iy \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_clib.inc \
	...
	-create-app -o $(BUILD_PATH)/FULL_vg5k_less_text.prg \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(FULL_FILES) \
```
I have tried other options with the same result.
Building with SCCZ80 is OK.

![vg5k_broken](https://user-images.githubusercontent.com/29057615/45542107-26389f80-b811-11e8-9843-a43cb6e95296.jpg)

**Comment by suborb** [comment]
A disassembly of the generated binary shows a couple of unexpected uses of ix:

- beeper.asm
- ___sdcc_enter_ix

Both of these should be using iy rather than ix. I suspect your problem is the latter (might also explain the zx81 problems)

I'll look into how they're assembled tonight, the latter should have been assembled with iy but appears not to have been.

**Comment by aralbrec** [comment]
The newlib separates the two cases:

**Comment by suborb** [comment]
This is a bit confusing (if only because the solution looks counterintuitive)

Classic --IXIY targets use libraries that have been assembled with --IXIY. Newlib defines __SDCC_IX and __SDCC_IY to swap them round rather than rely on the assembler flag.

So, for classic IXIY we need to compile newlib routines with SDCC_IX (so the assembler reads ix) but generates object code using iy.

I'll also need to check where we include newlib routines elsewhere to apply the same inverse logic.

**Comment by aralbrec** [comment]
SDCC_IX and SDCC_IY choose between two different c interfaces.  SDCC_IY gives IX to the compiler and assumes the library has exclusive use of IY.  It is made with the IXIY flag but it is not equivalent to SDCC_IX built with IXIY.

I would have thought it would work properly if the sdcc_ix library is used with __SDCC and __SDCC_IX defined.  Then you can choose to build with or without IXIY.

**Comment by Fabrizio-Caruso** [comment]
I confirm that this issue is solved but not other sdcc issues in my builds.
For example #817 has not been solved (I still need --max-alloc to get a fully working binary).
